# Generated by Django 4.2.9 on 2025-12-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shop_name", models.CharField(max_length=255)),
                ("shop_slug", models.SlugField(unique=True)),
                ("shop_description", models.TextField(blank=True)),
                (
                    "shop_image",
                    models.ImageField(blank=True, null=True, upload_to="shop_images/"),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("banned", "Banned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("bank_account_holder", models.CharField(max_length=255)),
                ("bank_name", models.CharField(max_length=255)),
                ("bank_account_number", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Seller",
                "verbose_name_plural": "Sellers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SellerSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan_type", models.CharField(default="monthly", max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=9.99, max_digits=10),
                ),
                ("renewal_date", models.DateField()),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="sellers.seller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seller Subscription",
                "verbose_name_plural": "Seller Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
    ]
