# Generated by Django 5.2.16 on 2026-07-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="last_emailed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
