# Generated by Django 5.2.10 on 2026-04-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_add_category_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
            },
        ),
        migrations.AddField(
            model_name="productcategory",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
