# Generated by Django 5.2.10 on 2026-04-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_add_category_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="productcategory",
            unique_together={("name", "parent")},
        ),
    ]
