# Generated by Django 5.2.10 on 2026-05-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_category_name_unique_per_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Nacrt"),
                    ("published", "Objavljeno"),
                    ("sold", "Prodato"),
                    ("archived", "Arhivirano"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
